// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_protocol.proto

#include "rpc_protocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb {
namespace rpc {
}  // namespace rpc
}  // namespace pb
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_rpc_5fprotocol_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_rpc_5fprotocol_2eproto = nullptr;
const uint32_t TableStruct_rpc_5fprotocol_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_rpc_5fprotocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022rpc_protocol.proto\022\006pb.rpc*N\n\013RPCProto"
  "col\022\017\n\013OP_RPC_None\020\000\022\024\n\017OP_RPC_EchoTest\020"
  "\351\007\022\030\n\023OP_RPC_LoginPending\020\321\017b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_rpc_5fprotocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_rpc_5fprotocol_2eproto = {
    false, false, 116, descriptor_table_protodef_rpc_5fprotocol_2eproto,
    "rpc_protocol.proto",
    &descriptor_table_rpc_5fprotocol_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_rpc_5fprotocol_2eproto::offsets,
    nullptr, file_level_enum_descriptors_rpc_5fprotocol_2eproto,
    file_level_service_descriptors_rpc_5fprotocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_rpc_5fprotocol_2eproto_getter() {
  return &descriptor_table_rpc_5fprotocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_rpc_5fprotocol_2eproto(&descriptor_table_rpc_5fprotocol_2eproto);
namespace pb {
namespace rpc {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RPCProtocol_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_rpc_5fprotocol_2eproto);
  return file_level_enum_descriptors_rpc_5fprotocol_2eproto[0];
}
bool RPCProtocol_IsValid(int value) {
  switch (value) {
    case 0:
    case 1001:
    case 2001:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace rpc
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
