// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pub_sub_protocol.proto

#include "pub_sub_protocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb {
namespace pub_sub {
}  // namespace pub_sub
}  // namespace pb
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_pub_5fsub_5fprotocol_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_pub_5fsub_5fprotocol_2eproto = nullptr;
const uint32_t TableStruct_pub_5fsub_5fprotocol_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_pub_5fsub_5fprotocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026pub_sub_protocol.proto\022\npb.pub_sub*<\n\014"
  "PubSub_Topic\022\022\n\016OP_PubSub_None\020\000\022\030\n\023OP_P"
  "ubSub_TestTopic\020\351\007b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_pub_5fsub_5fprotocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_pub_5fsub_5fprotocol_2eproto = {
    false, false, 106, descriptor_table_protodef_pub_5fsub_5fprotocol_2eproto,
    "pub_sub_protocol.proto",
    &descriptor_table_pub_5fsub_5fprotocol_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_pub_5fsub_5fprotocol_2eproto::offsets,
    nullptr, file_level_enum_descriptors_pub_5fsub_5fprotocol_2eproto,
    file_level_service_descriptors_pub_5fsub_5fprotocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_pub_5fsub_5fprotocol_2eproto_getter() {
  return &descriptor_table_pub_5fsub_5fprotocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_pub_5fsub_5fprotocol_2eproto(&descriptor_table_pub_5fsub_5fprotocol_2eproto);
namespace pb {
namespace pub_sub {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PubSub_Topic_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_pub_5fsub_5fprotocol_2eproto);
  return file_level_enum_descriptors_pub_5fsub_5fprotocol_2eproto[0];
}
bool PubSub_Topic_IsValid(int value) {
  switch (value) {
    case 0:
    case 1001:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pub_sub
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
