// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pub_sub_test.proto

#include "pub_sub_test.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pb {
namespace pub_sub {
PROTOBUF_CONSTEXPR PubSub_TestTopic::PubSub_TestTopic(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.value2_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value1_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PubSub_TestTopicDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PubSub_TestTopicDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PubSub_TestTopicDefaultTypeInternal() {}
  union {
    PubSub_TestTopic _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PubSub_TestTopicDefaultTypeInternal _PubSub_TestTopic_default_instance_;
}  // namespace pub_sub
}  // namespace pb
static ::_pb::Metadata file_level_metadata_pub_5fsub_5ftest_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_pub_5fsub_5ftest_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_pub_5fsub_5ftest_2eproto = nullptr;

const uint32_t TableStruct_pub_5fsub_5ftest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::pub_sub::PubSub_TestTopic, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::pb::pub_sub::PubSub_TestTopic, _impl_.value1_),
  PROTOBUF_FIELD_OFFSET(::pb::pub_sub::PubSub_TestTopic, _impl_.value2_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::pb::pub_sub::PubSub_TestTopic)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::pb::pub_sub::_PubSub_TestTopic_default_instance_._instance,
};

const char descriptor_table_protodef_pub_5fsub_5ftest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022pub_sub_test.proto\022\npb.pub_sub\"2\n\020PubS"
  "ub_TestTopic\022\016\n\006value1\030\001 \001(\004\022\016\n\006value2\030\002"
  " \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_pub_5fsub_5ftest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_pub_5fsub_5ftest_2eproto = {
    false, false, 92, descriptor_table_protodef_pub_5fsub_5ftest_2eproto,
    "pub_sub_test.proto",
    &descriptor_table_pub_5fsub_5ftest_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_pub_5fsub_5ftest_2eproto::offsets,
    file_level_metadata_pub_5fsub_5ftest_2eproto, file_level_enum_descriptors_pub_5fsub_5ftest_2eproto,
    file_level_service_descriptors_pub_5fsub_5ftest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_pub_5fsub_5ftest_2eproto_getter() {
  return &descriptor_table_pub_5fsub_5ftest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_pub_5fsub_5ftest_2eproto(&descriptor_table_pub_5fsub_5ftest_2eproto);
namespace pb {
namespace pub_sub {

// ===================================================================

class PubSub_TestTopic::_Internal {
 public:
};

PubSub_TestTopic::PubSub_TestTopic(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:pb.pub_sub.PubSub_TestTopic)
}
PubSub_TestTopic::PubSub_TestTopic(const PubSub_TestTopic& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PubSub_TestTopic* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value2_){}
    , decltype(_impl_.value1_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.value2_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value2_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value2().empty()) {
    _this->_impl_.value2_.Set(from._internal_value2(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.value1_ = from._impl_.value1_;
  // @@protoc_insertion_point(copy_constructor:pb.pub_sub.PubSub_TestTopic)
}

inline void PubSub_TestTopic::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.value2_){}
    , decltype(_impl_.value1_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.value2_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value2_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PubSub_TestTopic::~PubSub_TestTopic() {
  // @@protoc_insertion_point(destructor:pb.pub_sub.PubSub_TestTopic)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PubSub_TestTopic::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.value2_.Destroy();
}

void PubSub_TestTopic::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PubSub_TestTopic::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.pub_sub.PubSub_TestTopic)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value2_.ClearToEmpty();
  _impl_.value1_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PubSub_TestTopic::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 value1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.value1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string value2 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_value2();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "pb.pub_sub.PubSub_TestTopic.value2"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PubSub_TestTopic::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.pub_sub.PubSub_TestTopic)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 value1 = 1;
  if (this->_internal_value1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_value1(), target);
  }

  // string value2 = 2;
  if (!this->_internal_value2().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_value2().data(), static_cast<int>(this->_internal_value2().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pb.pub_sub.PubSub_TestTopic.value2");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_value2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.pub_sub.PubSub_TestTopic)
  return target;
}

size_t PubSub_TestTopic::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.pub_sub.PubSub_TestTopic)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string value2 = 2;
  if (!this->_internal_value2().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_value2());
  }

  // uint64 value1 = 1;
  if (this->_internal_value1() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_value1());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PubSub_TestTopic::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PubSub_TestTopic::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PubSub_TestTopic::GetClassData() const { return &_class_data_; }


void PubSub_TestTopic::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PubSub_TestTopic*>(&to_msg);
  auto& from = static_cast<const PubSub_TestTopic&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb.pub_sub.PubSub_TestTopic)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value2().empty()) {
    _this->_internal_set_value2(from._internal_value2());
  }
  if (from._internal_value1() != 0) {
    _this->_internal_set_value1(from._internal_value1());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PubSub_TestTopic::CopyFrom(const PubSub_TestTopic& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.pub_sub.PubSub_TestTopic)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PubSub_TestTopic::IsInitialized() const {
  return true;
}

void PubSub_TestTopic::InternalSwap(PubSub_TestTopic* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.value2_, lhs_arena,
      &other->_impl_.value2_, rhs_arena
  );
  swap(_impl_.value1_, other->_impl_.value1_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PubSub_TestTopic::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pub_5fsub_5ftest_2eproto_getter, &descriptor_table_pub_5fsub_5ftest_2eproto_once,
      file_level_metadata_pub_5fsub_5ftest_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pub_sub
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb::pub_sub::PubSub_TestTopic*
Arena::CreateMaybeMessage< ::pb::pub_sub::PubSub_TestTopic >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pb::pub_sub::PubSub_TestTopic >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
