# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta_enum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmeta_enum.proto\x12\x12\x61pollo.cyber.proto*{\n\x0bSectionType\x12\x12\n\x0eSECTION_HEADER\x10\x00\x12\x18\n\x14SECTION_CHUNK_HEADER\x10\x01\x12\x16\n\x12SECTION_CHUNK_BODY\x10\x02\x12\x11\n\rSECTION_INDEX\x10\x03\x12\x13\n\x0fSECTION_CHANNEL\x10\x04*E\n\x0c\x43ompressType\x12\x11\n\rCOMPRESS_NONE\x10\x00\x12\x10\n\x0c\x43OMPRESS_BZ2\x10\x01\x12\x10\n\x0c\x43OMPRESS_LZ4\x10\x02*Q\n\tParamType\x12\x0b\n\x07NOT_SET\x10\x00\x12\x08\n\x04\x42OOL\x10\x01\x12\x07\n\x03INT\x10\x02\x12\n\n\x06\x44OUBLE\x10\x03\x12\n\n\x06STRING\x10\x04\x12\x0c\n\x08PROTOBUF\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meta_enum_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SECTIONTYPE._serialized_start=39
  _SECTIONTYPE._serialized_end=162
  _COMPRESSTYPE._serialized_start=164
  _COMPRESSTYPE._serialized_end=233
  _PARAMTYPE._serialized_start=235
  _PARAMTYPE._serialized_end=316
# @@protoc_insertion_point(module_scope)
