// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_server_msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_role_5fserver_5fmsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_role_5fserver_5fmsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_role_5fserver_5fmsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_role_5fserver_5fmsg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_role_5fserver_5fmsg_2eproto;
namespace role_msg {
class AGENT_SEQ_ID;
struct AGENT_SEQ_IDDefaultTypeInternal;
extern AGENT_SEQ_IDDefaultTypeInternal _AGENT_SEQ_ID_default_instance_;
class ROLE_SUMMARY;
struct ROLE_SUMMARYDefaultTypeInternal;
extern ROLE_SUMMARYDefaultTypeInternal _ROLE_SUMMARY_default_instance_;
}  // namespace role_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::role_msg::AGENT_SEQ_ID* Arena::CreateMaybeMessage<::role_msg::AGENT_SEQ_ID>(Arena*);
template<> ::role_msg::ROLE_SUMMARY* Arena::CreateMaybeMessage<::role_msg::ROLE_SUMMARY>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace role_msg {

// ===================================================================

class ROLE_SUMMARY final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:role_msg.ROLE_SUMMARY) */ {
 public:
  inline ROLE_SUMMARY() : ROLE_SUMMARY(nullptr) {}
  ~ROLE_SUMMARY() override;
  explicit PROTOBUF_CONSTEXPR ROLE_SUMMARY(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ROLE_SUMMARY(const ROLE_SUMMARY& from);
  ROLE_SUMMARY(ROLE_SUMMARY&& from) noexcept
    : ROLE_SUMMARY() {
    *this = ::std::move(from);
  }

  inline ROLE_SUMMARY& operator=(const ROLE_SUMMARY& from) {
    CopyFrom(from);
    return *this;
  }
  inline ROLE_SUMMARY& operator=(ROLE_SUMMARY&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ROLE_SUMMARY& default_instance() {
    return *internal_default_instance();
  }
  static inline const ROLE_SUMMARY* internal_default_instance() {
    return reinterpret_cast<const ROLE_SUMMARY*>(
               &_ROLE_SUMMARY_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ROLE_SUMMARY& a, ROLE_SUMMARY& b) {
    a.Swap(&b);
  }
  inline void Swap(ROLE_SUMMARY* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ROLE_SUMMARY* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ROLE_SUMMARY* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ROLE_SUMMARY>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ROLE_SUMMARY& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ROLE_SUMMARY& from) {
    ROLE_SUMMARY::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ROLE_SUMMARY* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "role_msg.ROLE_SUMMARY";
  }
  protected:
  explicit ROLE_SUMMARY(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLootHistoryFieldNumber = 26,
    kNameFieldNumber = 2,
    kFaceFieldNumber = 5,
    kGuildNameFieldNumber = 8,
    kGuildShortNameFieldNumber = 20,
    kUserIdFieldNumber = 1,
    kFightingPowerFieldNumber = 4,
    kLevelFieldNumber = 3,
    kLanguageTypeFieldNumber = 9,
    kGuildIdFieldNumber = 7,
    kHeroPowerFieldNumber = 10,
    kSoldierPowerFieldNumber = 11,
    kBuildingPowerFieldNumber = 12,
    kOnlineFlagFieldNumber = 6,
    kRecordPowerRankFieldNumber = 17,
    kGuildRankFieldNumber = 13,
    kSurveyExpireTimeFieldNumber = 14,
    kPowerRankFieldNumber = 15,
    kBestPowerRankFieldNumber = 16,
    kGuildServerIdFieldNumber = 18,
    kGuildLanguageFieldNumber = 19,
    kLootDefenseTimeFieldNumber = 22,
    kLootAttackTimeFieldNumber = 23,
    kLootLockOwnerFieldNumber = 24,
    kCityCenterLevelFieldNumber = 21,
    kOnlineServerTypeFieldNumber = 27,
    kLootLockAtFieldNumber = 25,
    kOnlineServerIdFieldNumber = 28,
    kFantasiaChapterFieldNumber = 29,
    kFantasiaChapterPassFieldNumber = 30,
    kRegisterTimeFieldNumber = 31,
    kSeasonPointPeakFieldNumber = 32,
    kLootWinTimesFieldNumber = 33,
    kExcludedPowerFieldNumber = 34,
    kLoginTimeFieldNumber = 36,
    kLoginMainLogicIdFieldNumber = 35,
  };
  // repeated uint64 loot_history = 26;
  int loot_history_size() const;
  private:
  int _internal_loot_history_size() const;
  public:
  void clear_loot_history();
  private:
  uint64_t _internal_loot_history(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      _internal_loot_history() const;
  void _internal_add_loot_history(uint64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      _internal_mutable_loot_history();
  public:
  uint64_t loot_history(int index) const;
  void set_loot_history(int index, uint64_t value);
  void add_loot_history(uint64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      loot_history() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      mutable_loot_history();

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string face = 5;
  void clear_face();
  const std::string& face() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_face(ArgT0&& arg0, ArgT... args);
  std::string* mutable_face();
  PROTOBUF_NODISCARD std::string* release_face();
  void set_allocated_face(std::string* face);
  private:
  const std::string& _internal_face() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_face(const std::string& value);
  std::string* _internal_mutable_face();
  public:

  // string guild_name = 8;
  void clear_guild_name();
  const std::string& guild_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_guild_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_guild_name();
  PROTOBUF_NODISCARD std::string* release_guild_name();
  void set_allocated_guild_name(std::string* guild_name);
  private:
  const std::string& _internal_guild_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_guild_name(const std::string& value);
  std::string* _internal_mutable_guild_name();
  public:

  // string guild_short_name = 20;
  void clear_guild_short_name();
  const std::string& guild_short_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_guild_short_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_guild_short_name();
  PROTOBUF_NODISCARD std::string* release_guild_short_name();
  void set_allocated_guild_short_name(std::string* guild_short_name);
  private:
  const std::string& _internal_guild_short_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_guild_short_name(const std::string& value);
  std::string* _internal_mutable_guild_short_name();
  public:

  // uint64 user_id = 1;
  void clear_user_id();
  uint64_t user_id() const;
  void set_user_id(uint64_t value);
  private:
  uint64_t _internal_user_id() const;
  void _internal_set_user_id(uint64_t value);
  public:

  // uint64 fighting_power = 4;
  void clear_fighting_power();
  uint64_t fighting_power() const;
  void set_fighting_power(uint64_t value);
  private:
  uint64_t _internal_fighting_power() const;
  void _internal_set_fighting_power(uint64_t value);
  public:

  // int32 level = 3;
  void clear_level();
  int32_t level() const;
  void set_level(int32_t value);
  private:
  int32_t _internal_level() const;
  void _internal_set_level(int32_t value);
  public:

  // int32 language_type = 9;
  void clear_language_type();
  int32_t language_type() const;
  void set_language_type(int32_t value);
  private:
  int32_t _internal_language_type() const;
  void _internal_set_language_type(int32_t value);
  public:

  // uint64 guild_id = 7;
  void clear_guild_id();
  uint64_t guild_id() const;
  void set_guild_id(uint64_t value);
  private:
  uint64_t _internal_guild_id() const;
  void _internal_set_guild_id(uint64_t value);
  public:

  // uint64 hero_power = 10;
  void clear_hero_power();
  uint64_t hero_power() const;
  void set_hero_power(uint64_t value);
  private:
  uint64_t _internal_hero_power() const;
  void _internal_set_hero_power(uint64_t value);
  public:

  // uint64 soldier_power = 11;
  void clear_soldier_power();
  uint64_t soldier_power() const;
  void set_soldier_power(uint64_t value);
  private:
  uint64_t _internal_soldier_power() const;
  void _internal_set_soldier_power(uint64_t value);
  public:

  // uint64 building_power = 12;
  void clear_building_power();
  uint64_t building_power() const;
  void set_building_power(uint64_t value);
  private:
  uint64_t _internal_building_power() const;
  void _internal_set_building_power(uint64_t value);
  public:

  // bool online_flag = 6;
  void clear_online_flag();
  bool online_flag() const;
  void set_online_flag(bool value);
  private:
  bool _internal_online_flag() const;
  void _internal_set_online_flag(bool value);
  public:

  // bool record_power_rank = 17;
  void clear_record_power_rank();
  bool record_power_rank() const;
  void set_record_power_rank(bool value);
  private:
  bool _internal_record_power_rank() const;
  void _internal_set_record_power_rank(bool value);
  public:

  // uint32 guild_rank = 13;
  void clear_guild_rank();
  uint32_t guild_rank() const;
  void set_guild_rank(uint32_t value);
  private:
  uint32_t _internal_guild_rank() const;
  void _internal_set_guild_rank(uint32_t value);
  public:

  // uint64 survey_expire_time = 14;
  void clear_survey_expire_time();
  uint64_t survey_expire_time() const;
  void set_survey_expire_time(uint64_t value);
  private:
  uint64_t _internal_survey_expire_time() const;
  void _internal_set_survey_expire_time(uint64_t value);
  public:

  // int32 power_rank = 15;
  void clear_power_rank();
  int32_t power_rank() const;
  void set_power_rank(int32_t value);
  private:
  int32_t _internal_power_rank() const;
  void _internal_set_power_rank(int32_t value);
  public:

  // int32 best_power_rank = 16;
  void clear_best_power_rank();
  int32_t best_power_rank() const;
  void set_best_power_rank(int32_t value);
  private:
  int32_t _internal_best_power_rank() const;
  void _internal_set_best_power_rank(int32_t value);
  public:

  // int32 guild_server_id = 18;
  void clear_guild_server_id();
  int32_t guild_server_id() const;
  void set_guild_server_id(int32_t value);
  private:
  int32_t _internal_guild_server_id() const;
  void _internal_set_guild_server_id(int32_t value);
  public:

  // int32 guild_language = 19;
  void clear_guild_language();
  int32_t guild_language() const;
  void set_guild_language(int32_t value);
  private:
  int32_t _internal_guild_language() const;
  void _internal_set_guild_language(int32_t value);
  public:

  // uint64 loot_defense_time = 22;
  void clear_loot_defense_time();
  uint64_t loot_defense_time() const;
  void set_loot_defense_time(uint64_t value);
  private:
  uint64_t _internal_loot_defense_time() const;
  void _internal_set_loot_defense_time(uint64_t value);
  public:

  // uint64 loot_attack_time = 23;
  void clear_loot_attack_time();
  uint64_t loot_attack_time() const;
  void set_loot_attack_time(uint64_t value);
  private:
  uint64_t _internal_loot_attack_time() const;
  void _internal_set_loot_attack_time(uint64_t value);
  public:

  // uint64 loot_lock_owner = 24;
  void clear_loot_lock_owner();
  uint64_t loot_lock_owner() const;
  void set_loot_lock_owner(uint64_t value);
  private:
  uint64_t _internal_loot_lock_owner() const;
  void _internal_set_loot_lock_owner(uint64_t value);
  public:

  // uint32 city_center_level = 21;
  void clear_city_center_level();
  uint32_t city_center_level() const;
  void set_city_center_level(uint32_t value);
  private:
  uint32_t _internal_city_center_level() const;
  void _internal_set_city_center_level(uint32_t value);
  public:

  // uint32 online_server_type = 27;
  void clear_online_server_type();
  uint32_t online_server_type() const;
  void set_online_server_type(uint32_t value);
  private:
  uint32_t _internal_online_server_type() const;
  void _internal_set_online_server_type(uint32_t value);
  public:

  // uint64 loot_lock_at = 25;
  void clear_loot_lock_at();
  uint64_t loot_lock_at() const;
  void set_loot_lock_at(uint64_t value);
  private:
  uint64_t _internal_loot_lock_at() const;
  void _internal_set_loot_lock_at(uint64_t value);
  public:

  // uint32 online_server_id = 28;
  void clear_online_server_id();
  uint32_t online_server_id() const;
  void set_online_server_id(uint32_t value);
  private:
  uint32_t _internal_online_server_id() const;
  void _internal_set_online_server_id(uint32_t value);
  public:

  // uint32 fantasia_chapter = 29;
  void clear_fantasia_chapter();
  uint32_t fantasia_chapter() const;
  void set_fantasia_chapter(uint32_t value);
  private:
  uint32_t _internal_fantasia_chapter() const;
  void _internal_set_fantasia_chapter(uint32_t value);
  public:

  // uint64 fantasia_chapter_pass = 30;
  void clear_fantasia_chapter_pass();
  uint64_t fantasia_chapter_pass() const;
  void set_fantasia_chapter_pass(uint64_t value);
  private:
  uint64_t _internal_fantasia_chapter_pass() const;
  void _internal_set_fantasia_chapter_pass(uint64_t value);
  public:

  // uint64 register_time = 31;
  void clear_register_time();
  uint64_t register_time() const;
  void set_register_time(uint64_t value);
  private:
  uint64_t _internal_register_time() const;
  void _internal_set_register_time(uint64_t value);
  public:

  // int32 season_point_peak = 32;
  void clear_season_point_peak();
  int32_t season_point_peak() const;
  void set_season_point_peak(int32_t value);
  private:
  int32_t _internal_season_point_peak() const;
  void _internal_set_season_point_peak(int32_t value);
  public:

  // uint32 loot_win_times = 33;
  void clear_loot_win_times();
  uint32_t loot_win_times() const;
  void set_loot_win_times(uint32_t value);
  private:
  uint32_t _internal_loot_win_times() const;
  void _internal_set_loot_win_times(uint32_t value);
  public:

  // uint64 excluded_power = 34;
  void clear_excluded_power();
  uint64_t excluded_power() const;
  void set_excluded_power(uint64_t value);
  private:
  uint64_t _internal_excluded_power() const;
  void _internal_set_excluded_power(uint64_t value);
  public:

  // uint64 login_time = 36;
  void clear_login_time();
  uint64_t login_time() const;
  void set_login_time(uint64_t value);
  private:
  uint64_t _internal_login_time() const;
  void _internal_set_login_time(uint64_t value);
  public:

  // uint32 login_main_logic_id = 35;
  void clear_login_main_logic_id();
  uint32_t login_main_logic_id() const;
  void set_login_main_logic_id(uint32_t value);
  private:
  uint32_t _internal_login_main_logic_id() const;
  void _internal_set_login_main_logic_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:role_msg.ROLE_SUMMARY)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t > loot_history_;
    mutable std::atomic<int> _loot_history_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr face_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr guild_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr guild_short_name_;
    uint64_t user_id_;
    uint64_t fighting_power_;
    int32_t level_;
    int32_t language_type_;
    uint64_t guild_id_;
    uint64_t hero_power_;
    uint64_t soldier_power_;
    uint64_t building_power_;
    bool online_flag_;
    bool record_power_rank_;
    uint32_t guild_rank_;
    uint64_t survey_expire_time_;
    int32_t power_rank_;
    int32_t best_power_rank_;
    int32_t guild_server_id_;
    int32_t guild_language_;
    uint64_t loot_defense_time_;
    uint64_t loot_attack_time_;
    uint64_t loot_lock_owner_;
    uint32_t city_center_level_;
    uint32_t online_server_type_;
    uint64_t loot_lock_at_;
    uint32_t online_server_id_;
    uint32_t fantasia_chapter_;
    uint64_t fantasia_chapter_pass_;
    uint64_t register_time_;
    int32_t season_point_peak_;
    uint32_t loot_win_times_;
    uint64_t excluded_power_;
    uint64_t login_time_;
    uint32_t login_main_logic_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_role_5fserver_5fmsg_2eproto;
};
// -------------------------------------------------------------------

class AGENT_SEQ_ID final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:role_msg.AGENT_SEQ_ID) */ {
 public:
  inline AGENT_SEQ_ID() : AGENT_SEQ_ID(nullptr) {}
  ~AGENT_SEQ_ID() override;
  explicit PROTOBUF_CONSTEXPR AGENT_SEQ_ID(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AGENT_SEQ_ID(const AGENT_SEQ_ID& from);
  AGENT_SEQ_ID(AGENT_SEQ_ID&& from) noexcept
    : AGENT_SEQ_ID() {
    *this = ::std::move(from);
  }

  inline AGENT_SEQ_ID& operator=(const AGENT_SEQ_ID& from) {
    CopyFrom(from);
    return *this;
  }
  inline AGENT_SEQ_ID& operator=(AGENT_SEQ_ID&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AGENT_SEQ_ID& default_instance() {
    return *internal_default_instance();
  }
  static inline const AGENT_SEQ_ID* internal_default_instance() {
    return reinterpret_cast<const AGENT_SEQ_ID*>(
               &_AGENT_SEQ_ID_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AGENT_SEQ_ID& a, AGENT_SEQ_ID& b) {
    a.Swap(&b);
  }
  inline void Swap(AGENT_SEQ_ID* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AGENT_SEQ_ID* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AGENT_SEQ_ID* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AGENT_SEQ_ID>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AGENT_SEQ_ID& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AGENT_SEQ_ID& from) {
    AGENT_SEQ_ID::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AGENT_SEQ_ID* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "role_msg.AGENT_SEQ_ID";
  }
  protected:
  explicit AGENT_SEQ_ID(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSeqIdFieldNumber = 1,
  };
  // uint64 seq_id = 1;
  void clear_seq_id();
  uint64_t seq_id() const;
  void set_seq_id(uint64_t value);
  private:
  uint64_t _internal_seq_id() const;
  void _internal_set_seq_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:role_msg.AGENT_SEQ_ID)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t seq_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_role_5fserver_5fmsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ROLE_SUMMARY

// uint64 user_id = 1;
inline void ROLE_SUMMARY::clear_user_id() {
  _impl_.user_id_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_user_id() const {
  return _impl_.user_id_;
}
inline uint64_t ROLE_SUMMARY::user_id() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.user_id)
  return _internal_user_id();
}
inline void ROLE_SUMMARY::_internal_set_user_id(uint64_t value) {
  
  _impl_.user_id_ = value;
}
inline void ROLE_SUMMARY::set_user_id(uint64_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.user_id)
}

// string name = 2;
inline void ROLE_SUMMARY::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& ROLE_SUMMARY::name() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ROLE_SUMMARY::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.name)
}
inline std::string* ROLE_SUMMARY::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:role_msg.ROLE_SUMMARY.name)
  return _s;
}
inline const std::string& ROLE_SUMMARY::_internal_name() const {
  return _impl_.name_.Get();
}
inline void ROLE_SUMMARY::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* ROLE_SUMMARY::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* ROLE_SUMMARY::release_name() {
  // @@protoc_insertion_point(field_release:role_msg.ROLE_SUMMARY.name)
  return _impl_.name_.Release();
}
inline void ROLE_SUMMARY::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:role_msg.ROLE_SUMMARY.name)
}

// int32 level = 3;
inline void ROLE_SUMMARY::clear_level() {
  _impl_.level_ = 0;
}
inline int32_t ROLE_SUMMARY::_internal_level() const {
  return _impl_.level_;
}
inline int32_t ROLE_SUMMARY::level() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.level)
  return _internal_level();
}
inline void ROLE_SUMMARY::_internal_set_level(int32_t value) {
  
  _impl_.level_ = value;
}
inline void ROLE_SUMMARY::set_level(int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.level)
}

// uint64 fighting_power = 4;
inline void ROLE_SUMMARY::clear_fighting_power() {
  _impl_.fighting_power_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_fighting_power() const {
  return _impl_.fighting_power_;
}
inline uint64_t ROLE_SUMMARY::fighting_power() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.fighting_power)
  return _internal_fighting_power();
}
inline void ROLE_SUMMARY::_internal_set_fighting_power(uint64_t value) {
  
  _impl_.fighting_power_ = value;
}
inline void ROLE_SUMMARY::set_fighting_power(uint64_t value) {
  _internal_set_fighting_power(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.fighting_power)
}

// string face = 5;
inline void ROLE_SUMMARY::clear_face() {
  _impl_.face_.ClearToEmpty();
}
inline const std::string& ROLE_SUMMARY::face() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.face)
  return _internal_face();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ROLE_SUMMARY::set_face(ArgT0&& arg0, ArgT... args) {
 
 _impl_.face_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.face)
}
inline std::string* ROLE_SUMMARY::mutable_face() {
  std::string* _s = _internal_mutable_face();
  // @@protoc_insertion_point(field_mutable:role_msg.ROLE_SUMMARY.face)
  return _s;
}
inline const std::string& ROLE_SUMMARY::_internal_face() const {
  return _impl_.face_.Get();
}
inline void ROLE_SUMMARY::_internal_set_face(const std::string& value) {
  
  _impl_.face_.Set(value, GetArenaForAllocation());
}
inline std::string* ROLE_SUMMARY::_internal_mutable_face() {
  
  return _impl_.face_.Mutable(GetArenaForAllocation());
}
inline std::string* ROLE_SUMMARY::release_face() {
  // @@protoc_insertion_point(field_release:role_msg.ROLE_SUMMARY.face)
  return _impl_.face_.Release();
}
inline void ROLE_SUMMARY::set_allocated_face(std::string* face) {
  if (face != nullptr) {
    
  } else {
    
  }
  _impl_.face_.SetAllocated(face, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.face_.IsDefault()) {
    _impl_.face_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:role_msg.ROLE_SUMMARY.face)
}

// bool online_flag = 6;
inline void ROLE_SUMMARY::clear_online_flag() {
  _impl_.online_flag_ = false;
}
inline bool ROLE_SUMMARY::_internal_online_flag() const {
  return _impl_.online_flag_;
}
inline bool ROLE_SUMMARY::online_flag() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.online_flag)
  return _internal_online_flag();
}
inline void ROLE_SUMMARY::_internal_set_online_flag(bool value) {
  
  _impl_.online_flag_ = value;
}
inline void ROLE_SUMMARY::set_online_flag(bool value) {
  _internal_set_online_flag(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.online_flag)
}

// uint64 guild_id = 7;
inline void ROLE_SUMMARY::clear_guild_id() {
  _impl_.guild_id_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_guild_id() const {
  return _impl_.guild_id_;
}
inline uint64_t ROLE_SUMMARY::guild_id() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.guild_id)
  return _internal_guild_id();
}
inline void ROLE_SUMMARY::_internal_set_guild_id(uint64_t value) {
  
  _impl_.guild_id_ = value;
}
inline void ROLE_SUMMARY::set_guild_id(uint64_t value) {
  _internal_set_guild_id(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.guild_id)
}

// string guild_name = 8;
inline void ROLE_SUMMARY::clear_guild_name() {
  _impl_.guild_name_.ClearToEmpty();
}
inline const std::string& ROLE_SUMMARY::guild_name() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.guild_name)
  return _internal_guild_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ROLE_SUMMARY::set_guild_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.guild_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.guild_name)
}
inline std::string* ROLE_SUMMARY::mutable_guild_name() {
  std::string* _s = _internal_mutable_guild_name();
  // @@protoc_insertion_point(field_mutable:role_msg.ROLE_SUMMARY.guild_name)
  return _s;
}
inline const std::string& ROLE_SUMMARY::_internal_guild_name() const {
  return _impl_.guild_name_.Get();
}
inline void ROLE_SUMMARY::_internal_set_guild_name(const std::string& value) {
  
  _impl_.guild_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ROLE_SUMMARY::_internal_mutable_guild_name() {
  
  return _impl_.guild_name_.Mutable(GetArenaForAllocation());
}
inline std::string* ROLE_SUMMARY::release_guild_name() {
  // @@protoc_insertion_point(field_release:role_msg.ROLE_SUMMARY.guild_name)
  return _impl_.guild_name_.Release();
}
inline void ROLE_SUMMARY::set_allocated_guild_name(std::string* guild_name) {
  if (guild_name != nullptr) {
    
  } else {
    
  }
  _impl_.guild_name_.SetAllocated(guild_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.guild_name_.IsDefault()) {
    _impl_.guild_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:role_msg.ROLE_SUMMARY.guild_name)
}

// int32 language_type = 9;
inline void ROLE_SUMMARY::clear_language_type() {
  _impl_.language_type_ = 0;
}
inline int32_t ROLE_SUMMARY::_internal_language_type() const {
  return _impl_.language_type_;
}
inline int32_t ROLE_SUMMARY::language_type() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.language_type)
  return _internal_language_type();
}
inline void ROLE_SUMMARY::_internal_set_language_type(int32_t value) {
  
  _impl_.language_type_ = value;
}
inline void ROLE_SUMMARY::set_language_type(int32_t value) {
  _internal_set_language_type(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.language_type)
}

// uint64 hero_power = 10;
inline void ROLE_SUMMARY::clear_hero_power() {
  _impl_.hero_power_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_hero_power() const {
  return _impl_.hero_power_;
}
inline uint64_t ROLE_SUMMARY::hero_power() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.hero_power)
  return _internal_hero_power();
}
inline void ROLE_SUMMARY::_internal_set_hero_power(uint64_t value) {
  
  _impl_.hero_power_ = value;
}
inline void ROLE_SUMMARY::set_hero_power(uint64_t value) {
  _internal_set_hero_power(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.hero_power)
}

// uint64 soldier_power = 11;
inline void ROLE_SUMMARY::clear_soldier_power() {
  _impl_.soldier_power_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_soldier_power() const {
  return _impl_.soldier_power_;
}
inline uint64_t ROLE_SUMMARY::soldier_power() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.soldier_power)
  return _internal_soldier_power();
}
inline void ROLE_SUMMARY::_internal_set_soldier_power(uint64_t value) {
  
  _impl_.soldier_power_ = value;
}
inline void ROLE_SUMMARY::set_soldier_power(uint64_t value) {
  _internal_set_soldier_power(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.soldier_power)
}

// uint64 building_power = 12;
inline void ROLE_SUMMARY::clear_building_power() {
  _impl_.building_power_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_building_power() const {
  return _impl_.building_power_;
}
inline uint64_t ROLE_SUMMARY::building_power() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.building_power)
  return _internal_building_power();
}
inline void ROLE_SUMMARY::_internal_set_building_power(uint64_t value) {
  
  _impl_.building_power_ = value;
}
inline void ROLE_SUMMARY::set_building_power(uint64_t value) {
  _internal_set_building_power(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.building_power)
}

// uint32 guild_rank = 13;
inline void ROLE_SUMMARY::clear_guild_rank() {
  _impl_.guild_rank_ = 0u;
}
inline uint32_t ROLE_SUMMARY::_internal_guild_rank() const {
  return _impl_.guild_rank_;
}
inline uint32_t ROLE_SUMMARY::guild_rank() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.guild_rank)
  return _internal_guild_rank();
}
inline void ROLE_SUMMARY::_internal_set_guild_rank(uint32_t value) {
  
  _impl_.guild_rank_ = value;
}
inline void ROLE_SUMMARY::set_guild_rank(uint32_t value) {
  _internal_set_guild_rank(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.guild_rank)
}

// uint64 survey_expire_time = 14;
inline void ROLE_SUMMARY::clear_survey_expire_time() {
  _impl_.survey_expire_time_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_survey_expire_time() const {
  return _impl_.survey_expire_time_;
}
inline uint64_t ROLE_SUMMARY::survey_expire_time() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.survey_expire_time)
  return _internal_survey_expire_time();
}
inline void ROLE_SUMMARY::_internal_set_survey_expire_time(uint64_t value) {
  
  _impl_.survey_expire_time_ = value;
}
inline void ROLE_SUMMARY::set_survey_expire_time(uint64_t value) {
  _internal_set_survey_expire_time(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.survey_expire_time)
}

// int32 power_rank = 15;
inline void ROLE_SUMMARY::clear_power_rank() {
  _impl_.power_rank_ = 0;
}
inline int32_t ROLE_SUMMARY::_internal_power_rank() const {
  return _impl_.power_rank_;
}
inline int32_t ROLE_SUMMARY::power_rank() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.power_rank)
  return _internal_power_rank();
}
inline void ROLE_SUMMARY::_internal_set_power_rank(int32_t value) {
  
  _impl_.power_rank_ = value;
}
inline void ROLE_SUMMARY::set_power_rank(int32_t value) {
  _internal_set_power_rank(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.power_rank)
}

// int32 best_power_rank = 16;
inline void ROLE_SUMMARY::clear_best_power_rank() {
  _impl_.best_power_rank_ = 0;
}
inline int32_t ROLE_SUMMARY::_internal_best_power_rank() const {
  return _impl_.best_power_rank_;
}
inline int32_t ROLE_SUMMARY::best_power_rank() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.best_power_rank)
  return _internal_best_power_rank();
}
inline void ROLE_SUMMARY::_internal_set_best_power_rank(int32_t value) {
  
  _impl_.best_power_rank_ = value;
}
inline void ROLE_SUMMARY::set_best_power_rank(int32_t value) {
  _internal_set_best_power_rank(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.best_power_rank)
}

// bool record_power_rank = 17;
inline void ROLE_SUMMARY::clear_record_power_rank() {
  _impl_.record_power_rank_ = false;
}
inline bool ROLE_SUMMARY::_internal_record_power_rank() const {
  return _impl_.record_power_rank_;
}
inline bool ROLE_SUMMARY::record_power_rank() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.record_power_rank)
  return _internal_record_power_rank();
}
inline void ROLE_SUMMARY::_internal_set_record_power_rank(bool value) {
  
  _impl_.record_power_rank_ = value;
}
inline void ROLE_SUMMARY::set_record_power_rank(bool value) {
  _internal_set_record_power_rank(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.record_power_rank)
}

// int32 guild_server_id = 18;
inline void ROLE_SUMMARY::clear_guild_server_id() {
  _impl_.guild_server_id_ = 0;
}
inline int32_t ROLE_SUMMARY::_internal_guild_server_id() const {
  return _impl_.guild_server_id_;
}
inline int32_t ROLE_SUMMARY::guild_server_id() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.guild_server_id)
  return _internal_guild_server_id();
}
inline void ROLE_SUMMARY::_internal_set_guild_server_id(int32_t value) {
  
  _impl_.guild_server_id_ = value;
}
inline void ROLE_SUMMARY::set_guild_server_id(int32_t value) {
  _internal_set_guild_server_id(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.guild_server_id)
}

// int32 guild_language = 19;
inline void ROLE_SUMMARY::clear_guild_language() {
  _impl_.guild_language_ = 0;
}
inline int32_t ROLE_SUMMARY::_internal_guild_language() const {
  return _impl_.guild_language_;
}
inline int32_t ROLE_SUMMARY::guild_language() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.guild_language)
  return _internal_guild_language();
}
inline void ROLE_SUMMARY::_internal_set_guild_language(int32_t value) {
  
  _impl_.guild_language_ = value;
}
inline void ROLE_SUMMARY::set_guild_language(int32_t value) {
  _internal_set_guild_language(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.guild_language)
}

// string guild_short_name = 20;
inline void ROLE_SUMMARY::clear_guild_short_name() {
  _impl_.guild_short_name_.ClearToEmpty();
}
inline const std::string& ROLE_SUMMARY::guild_short_name() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.guild_short_name)
  return _internal_guild_short_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ROLE_SUMMARY::set_guild_short_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.guild_short_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.guild_short_name)
}
inline std::string* ROLE_SUMMARY::mutable_guild_short_name() {
  std::string* _s = _internal_mutable_guild_short_name();
  // @@protoc_insertion_point(field_mutable:role_msg.ROLE_SUMMARY.guild_short_name)
  return _s;
}
inline const std::string& ROLE_SUMMARY::_internal_guild_short_name() const {
  return _impl_.guild_short_name_.Get();
}
inline void ROLE_SUMMARY::_internal_set_guild_short_name(const std::string& value) {
  
  _impl_.guild_short_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ROLE_SUMMARY::_internal_mutable_guild_short_name() {
  
  return _impl_.guild_short_name_.Mutable(GetArenaForAllocation());
}
inline std::string* ROLE_SUMMARY::release_guild_short_name() {
  // @@protoc_insertion_point(field_release:role_msg.ROLE_SUMMARY.guild_short_name)
  return _impl_.guild_short_name_.Release();
}
inline void ROLE_SUMMARY::set_allocated_guild_short_name(std::string* guild_short_name) {
  if (guild_short_name != nullptr) {
    
  } else {
    
  }
  _impl_.guild_short_name_.SetAllocated(guild_short_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.guild_short_name_.IsDefault()) {
    _impl_.guild_short_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:role_msg.ROLE_SUMMARY.guild_short_name)
}

// uint32 city_center_level = 21;
inline void ROLE_SUMMARY::clear_city_center_level() {
  _impl_.city_center_level_ = 0u;
}
inline uint32_t ROLE_SUMMARY::_internal_city_center_level() const {
  return _impl_.city_center_level_;
}
inline uint32_t ROLE_SUMMARY::city_center_level() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.city_center_level)
  return _internal_city_center_level();
}
inline void ROLE_SUMMARY::_internal_set_city_center_level(uint32_t value) {
  
  _impl_.city_center_level_ = value;
}
inline void ROLE_SUMMARY::set_city_center_level(uint32_t value) {
  _internal_set_city_center_level(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.city_center_level)
}

// uint64 loot_defense_time = 22;
inline void ROLE_SUMMARY::clear_loot_defense_time() {
  _impl_.loot_defense_time_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_loot_defense_time() const {
  return _impl_.loot_defense_time_;
}
inline uint64_t ROLE_SUMMARY::loot_defense_time() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.loot_defense_time)
  return _internal_loot_defense_time();
}
inline void ROLE_SUMMARY::_internal_set_loot_defense_time(uint64_t value) {
  
  _impl_.loot_defense_time_ = value;
}
inline void ROLE_SUMMARY::set_loot_defense_time(uint64_t value) {
  _internal_set_loot_defense_time(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.loot_defense_time)
}

// uint64 loot_attack_time = 23;
inline void ROLE_SUMMARY::clear_loot_attack_time() {
  _impl_.loot_attack_time_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_loot_attack_time() const {
  return _impl_.loot_attack_time_;
}
inline uint64_t ROLE_SUMMARY::loot_attack_time() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.loot_attack_time)
  return _internal_loot_attack_time();
}
inline void ROLE_SUMMARY::_internal_set_loot_attack_time(uint64_t value) {
  
  _impl_.loot_attack_time_ = value;
}
inline void ROLE_SUMMARY::set_loot_attack_time(uint64_t value) {
  _internal_set_loot_attack_time(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.loot_attack_time)
}

// uint64 loot_lock_owner = 24;
inline void ROLE_SUMMARY::clear_loot_lock_owner() {
  _impl_.loot_lock_owner_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_loot_lock_owner() const {
  return _impl_.loot_lock_owner_;
}
inline uint64_t ROLE_SUMMARY::loot_lock_owner() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.loot_lock_owner)
  return _internal_loot_lock_owner();
}
inline void ROLE_SUMMARY::_internal_set_loot_lock_owner(uint64_t value) {
  
  _impl_.loot_lock_owner_ = value;
}
inline void ROLE_SUMMARY::set_loot_lock_owner(uint64_t value) {
  _internal_set_loot_lock_owner(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.loot_lock_owner)
}

// uint64 loot_lock_at = 25;
inline void ROLE_SUMMARY::clear_loot_lock_at() {
  _impl_.loot_lock_at_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_loot_lock_at() const {
  return _impl_.loot_lock_at_;
}
inline uint64_t ROLE_SUMMARY::loot_lock_at() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.loot_lock_at)
  return _internal_loot_lock_at();
}
inline void ROLE_SUMMARY::_internal_set_loot_lock_at(uint64_t value) {
  
  _impl_.loot_lock_at_ = value;
}
inline void ROLE_SUMMARY::set_loot_lock_at(uint64_t value) {
  _internal_set_loot_lock_at(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.loot_lock_at)
}

// repeated uint64 loot_history = 26;
inline int ROLE_SUMMARY::_internal_loot_history_size() const {
  return _impl_.loot_history_.size();
}
inline int ROLE_SUMMARY::loot_history_size() const {
  return _internal_loot_history_size();
}
inline void ROLE_SUMMARY::clear_loot_history() {
  _impl_.loot_history_.Clear();
}
inline uint64_t ROLE_SUMMARY::_internal_loot_history(int index) const {
  return _impl_.loot_history_.Get(index);
}
inline uint64_t ROLE_SUMMARY::loot_history(int index) const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.loot_history)
  return _internal_loot_history(index);
}
inline void ROLE_SUMMARY::set_loot_history(int index, uint64_t value) {
  _impl_.loot_history_.Set(index, value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.loot_history)
}
inline void ROLE_SUMMARY::_internal_add_loot_history(uint64_t value) {
  _impl_.loot_history_.Add(value);
}
inline void ROLE_SUMMARY::add_loot_history(uint64_t value) {
  _internal_add_loot_history(value);
  // @@protoc_insertion_point(field_add:role_msg.ROLE_SUMMARY.loot_history)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
ROLE_SUMMARY::_internal_loot_history() const {
  return _impl_.loot_history_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
ROLE_SUMMARY::loot_history() const {
  // @@protoc_insertion_point(field_list:role_msg.ROLE_SUMMARY.loot_history)
  return _internal_loot_history();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
ROLE_SUMMARY::_internal_mutable_loot_history() {
  return &_impl_.loot_history_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
ROLE_SUMMARY::mutable_loot_history() {
  // @@protoc_insertion_point(field_mutable_list:role_msg.ROLE_SUMMARY.loot_history)
  return _internal_mutable_loot_history();
}

// uint32 online_server_type = 27;
inline void ROLE_SUMMARY::clear_online_server_type() {
  _impl_.online_server_type_ = 0u;
}
inline uint32_t ROLE_SUMMARY::_internal_online_server_type() const {
  return _impl_.online_server_type_;
}
inline uint32_t ROLE_SUMMARY::online_server_type() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.online_server_type)
  return _internal_online_server_type();
}
inline void ROLE_SUMMARY::_internal_set_online_server_type(uint32_t value) {
  
  _impl_.online_server_type_ = value;
}
inline void ROLE_SUMMARY::set_online_server_type(uint32_t value) {
  _internal_set_online_server_type(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.online_server_type)
}

// uint32 online_server_id = 28;
inline void ROLE_SUMMARY::clear_online_server_id() {
  _impl_.online_server_id_ = 0u;
}
inline uint32_t ROLE_SUMMARY::_internal_online_server_id() const {
  return _impl_.online_server_id_;
}
inline uint32_t ROLE_SUMMARY::online_server_id() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.online_server_id)
  return _internal_online_server_id();
}
inline void ROLE_SUMMARY::_internal_set_online_server_id(uint32_t value) {
  
  _impl_.online_server_id_ = value;
}
inline void ROLE_SUMMARY::set_online_server_id(uint32_t value) {
  _internal_set_online_server_id(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.online_server_id)
}

// uint32 fantasia_chapter = 29;
inline void ROLE_SUMMARY::clear_fantasia_chapter() {
  _impl_.fantasia_chapter_ = 0u;
}
inline uint32_t ROLE_SUMMARY::_internal_fantasia_chapter() const {
  return _impl_.fantasia_chapter_;
}
inline uint32_t ROLE_SUMMARY::fantasia_chapter() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.fantasia_chapter)
  return _internal_fantasia_chapter();
}
inline void ROLE_SUMMARY::_internal_set_fantasia_chapter(uint32_t value) {
  
  _impl_.fantasia_chapter_ = value;
}
inline void ROLE_SUMMARY::set_fantasia_chapter(uint32_t value) {
  _internal_set_fantasia_chapter(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.fantasia_chapter)
}

// uint64 fantasia_chapter_pass = 30;
inline void ROLE_SUMMARY::clear_fantasia_chapter_pass() {
  _impl_.fantasia_chapter_pass_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_fantasia_chapter_pass() const {
  return _impl_.fantasia_chapter_pass_;
}
inline uint64_t ROLE_SUMMARY::fantasia_chapter_pass() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.fantasia_chapter_pass)
  return _internal_fantasia_chapter_pass();
}
inline void ROLE_SUMMARY::_internal_set_fantasia_chapter_pass(uint64_t value) {
  
  _impl_.fantasia_chapter_pass_ = value;
}
inline void ROLE_SUMMARY::set_fantasia_chapter_pass(uint64_t value) {
  _internal_set_fantasia_chapter_pass(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.fantasia_chapter_pass)
}

// uint64 register_time = 31;
inline void ROLE_SUMMARY::clear_register_time() {
  _impl_.register_time_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_register_time() const {
  return _impl_.register_time_;
}
inline uint64_t ROLE_SUMMARY::register_time() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.register_time)
  return _internal_register_time();
}
inline void ROLE_SUMMARY::_internal_set_register_time(uint64_t value) {
  
  _impl_.register_time_ = value;
}
inline void ROLE_SUMMARY::set_register_time(uint64_t value) {
  _internal_set_register_time(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.register_time)
}

// int32 season_point_peak = 32;
inline void ROLE_SUMMARY::clear_season_point_peak() {
  _impl_.season_point_peak_ = 0;
}
inline int32_t ROLE_SUMMARY::_internal_season_point_peak() const {
  return _impl_.season_point_peak_;
}
inline int32_t ROLE_SUMMARY::season_point_peak() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.season_point_peak)
  return _internal_season_point_peak();
}
inline void ROLE_SUMMARY::_internal_set_season_point_peak(int32_t value) {
  
  _impl_.season_point_peak_ = value;
}
inline void ROLE_SUMMARY::set_season_point_peak(int32_t value) {
  _internal_set_season_point_peak(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.season_point_peak)
}

// uint32 loot_win_times = 33;
inline void ROLE_SUMMARY::clear_loot_win_times() {
  _impl_.loot_win_times_ = 0u;
}
inline uint32_t ROLE_SUMMARY::_internal_loot_win_times() const {
  return _impl_.loot_win_times_;
}
inline uint32_t ROLE_SUMMARY::loot_win_times() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.loot_win_times)
  return _internal_loot_win_times();
}
inline void ROLE_SUMMARY::_internal_set_loot_win_times(uint32_t value) {
  
  _impl_.loot_win_times_ = value;
}
inline void ROLE_SUMMARY::set_loot_win_times(uint32_t value) {
  _internal_set_loot_win_times(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.loot_win_times)
}

// uint64 excluded_power = 34;
inline void ROLE_SUMMARY::clear_excluded_power() {
  _impl_.excluded_power_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_excluded_power() const {
  return _impl_.excluded_power_;
}
inline uint64_t ROLE_SUMMARY::excluded_power() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.excluded_power)
  return _internal_excluded_power();
}
inline void ROLE_SUMMARY::_internal_set_excluded_power(uint64_t value) {
  
  _impl_.excluded_power_ = value;
}
inline void ROLE_SUMMARY::set_excluded_power(uint64_t value) {
  _internal_set_excluded_power(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.excluded_power)
}

// uint32 login_main_logic_id = 35;
inline void ROLE_SUMMARY::clear_login_main_logic_id() {
  _impl_.login_main_logic_id_ = 0u;
}
inline uint32_t ROLE_SUMMARY::_internal_login_main_logic_id() const {
  return _impl_.login_main_logic_id_;
}
inline uint32_t ROLE_SUMMARY::login_main_logic_id() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.login_main_logic_id)
  return _internal_login_main_logic_id();
}
inline void ROLE_SUMMARY::_internal_set_login_main_logic_id(uint32_t value) {
  
  _impl_.login_main_logic_id_ = value;
}
inline void ROLE_SUMMARY::set_login_main_logic_id(uint32_t value) {
  _internal_set_login_main_logic_id(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.login_main_logic_id)
}

// uint64 login_time = 36;
inline void ROLE_SUMMARY::clear_login_time() {
  _impl_.login_time_ = uint64_t{0u};
}
inline uint64_t ROLE_SUMMARY::_internal_login_time() const {
  return _impl_.login_time_;
}
inline uint64_t ROLE_SUMMARY::login_time() const {
  // @@protoc_insertion_point(field_get:role_msg.ROLE_SUMMARY.login_time)
  return _internal_login_time();
}
inline void ROLE_SUMMARY::_internal_set_login_time(uint64_t value) {
  
  _impl_.login_time_ = value;
}
inline void ROLE_SUMMARY::set_login_time(uint64_t value) {
  _internal_set_login_time(value);
  // @@protoc_insertion_point(field_set:role_msg.ROLE_SUMMARY.login_time)
}

// -------------------------------------------------------------------

// AGENT_SEQ_ID

// uint64 seq_id = 1;
inline void AGENT_SEQ_ID::clear_seq_id() {
  _impl_.seq_id_ = uint64_t{0u};
}
inline uint64_t AGENT_SEQ_ID::_internal_seq_id() const {
  return _impl_.seq_id_;
}
inline uint64_t AGENT_SEQ_ID::seq_id() const {
  // @@protoc_insertion_point(field_get:role_msg.AGENT_SEQ_ID.seq_id)
  return _internal_seq_id();
}
inline void AGENT_SEQ_ID::_internal_set_seq_id(uint64_t value) {
  
  _impl_.seq_id_ = value;
}
inline void AGENT_SEQ_ID::set_seq_id(uint64_t value) {
  _internal_set_seq_id(value);
  // @@protoc_insertion_point(field_set:role_msg.AGENT_SEQ_ID.seq_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace role_msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_role_5fserver_5fmsg_2eproto
