# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login_msg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login_msg.proto',
  package='login_msg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0flogin_msg.proto\x12\tlogin_msg\"\x9b\x01\n\x0fGameAccountInfo\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x14\n\x0cis_suspended\x18\x03 \x01(\x08\x12\x11\n\tis_banned\x18\x04 \x01(\x08\x12\x1a\n\x12suspension_expires\x18\x05 \x01(\x04\x12\x19\n\x11suspension_reason\x18\x06 \x01(\t\"D\n\x0fGameAccountList\x12\x31\n\rgame_accounts\x18\x01 \x03(\x0b\x32\x1a.login_msg.GameAccountInfo\"y\n\x1bMSG_REQUEST_ACCOUNT_LOGIN_L\x12\x13\n\x0bplatform_id\x18\x01 \x01(\t\x12\x12\n\nprogram_id\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\x12\n\naccount_id\x18\x04 \x01(\x04\x12\x0c\n\x04\x61uth\x18\x05 \x01(\t\"v\n\x1cMSG_RESPONSE_ACCOUNT_LOGIN_L\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x12\n\naccount_id\x18\x02 \x01(\x04\x12\x13\n\x0bsession_key\x18\x03 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\"3\n\x1aMSG_REQUEST_HANDSHAKE_INIT\x12\x15\n\rclient_random\x18\x01 \x01(\t\"]\n\x1bMSG_RESPONSE_HANDSHAKE_INIT\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x15\n\rserver_random\x18\x02 \x01(\t\x12\x12\n\npublic_key\x18\x03 \x01(\t\":\n!MSG_REQUEST_HANDSHAKE_ESTABLISHED\x12\x15\n\rencrypted_key\x18\x01 \x01(\x0c\"9\n\"MSG_RESPONSE_HANDSHAKE_ESTABLISHED\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\"Q\n\x18MSG_REQUEST_CLIENT_LOGIN\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x13\n\x0bsession_key\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x05\"\x85\x01\n\x19MSG_RESPONSE_CLIENT_LOGIN\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\x11\n\tis_newbie\x18\x04 \x01(\x08\x12\x0c\n\x04\x61mmo\x18\x05 \x01(\r\x12\x10\n\x08grenades\x18\x06 \x01(\r\"2\n\x10MSG_REQUEST_ECHO\x12\x0e\n\x06value1\x18\x01 \x01(\x04\x12\x0e\n\x06value2\x18\x02 \x01(\t\"3\n\x11MSG_RESPONSE_ECHO\x12\x0e\n\x06value1\x18\x01 \x01(\x04\x12\x0e\n\x06value2\x18\x02 \x01(\tb\x06proto3'
)




_GAMEACCOUNTINFO = _descriptor.Descriptor(
  name='GameAccountInfo',
  full_name='login_msg.GameAccountInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='login_msg.GameAccountInfo.account_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='login_msg.GameAccountInfo.display_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_suspended', full_name='login_msg.GameAccountInfo.is_suspended', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_banned', full_name='login_msg.GameAccountInfo.is_banned', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='suspension_expires', full_name='login_msg.GameAccountInfo.suspension_expires', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='suspension_reason', full_name='login_msg.GameAccountInfo.suspension_reason', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=186,
)


_GAMEACCOUNTLIST = _descriptor.Descriptor(
  name='GameAccountList',
  full_name='login_msg.GameAccountList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_accounts', full_name='login_msg.GameAccountList.game_accounts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=256,
)


_MSG_REQUEST_ACCOUNT_LOGIN_L = _descriptor.Descriptor(
  name='MSG_REQUEST_ACCOUNT_LOGIN_L',
  full_name='login_msg.MSG_REQUEST_ACCOUNT_LOGIN_L',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='platform_id', full_name='login_msg.MSG_REQUEST_ACCOUNT_LOGIN_L.platform_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='program_id', full_name='login_msg.MSG_REQUEST_ACCOUNT_LOGIN_L.program_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='login_msg.MSG_REQUEST_ACCOUNT_LOGIN_L.version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='login_msg.MSG_REQUEST_ACCOUNT_LOGIN_L.account_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth', full_name='login_msg.MSG_REQUEST_ACCOUNT_LOGIN_L.auth', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=379,
)


_MSG_RESPONSE_ACCOUNT_LOGIN_L = _descriptor.Descriptor(
  name='MSG_RESPONSE_ACCOUNT_LOGIN_L',
  full_name='login_msg.MSG_RESPONSE_ACCOUNT_LOGIN_L',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='login_msg.MSG_RESPONSE_ACCOUNT_LOGIN_L.status_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='login_msg.MSG_RESPONSE_ACCOUNT_LOGIN_L.account_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_key', full_name='login_msg.MSG_RESPONSE_ACCOUNT_LOGIN_L.session_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='login_msg.MSG_RESPONSE_ACCOUNT_LOGIN_L.ip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='login_msg.MSG_RESPONSE_ACCOUNT_LOGIN_L.port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=499,
)


_MSG_REQUEST_HANDSHAKE_INIT = _descriptor.Descriptor(
  name='MSG_REQUEST_HANDSHAKE_INIT',
  full_name='login_msg.MSG_REQUEST_HANDSHAKE_INIT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_random', full_name='login_msg.MSG_REQUEST_HANDSHAKE_INIT.client_random', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=552,
)


_MSG_RESPONSE_HANDSHAKE_INIT = _descriptor.Descriptor(
  name='MSG_RESPONSE_HANDSHAKE_INIT',
  full_name='login_msg.MSG_RESPONSE_HANDSHAKE_INIT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='login_msg.MSG_RESPONSE_HANDSHAKE_INIT.status_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_random', full_name='login_msg.MSG_RESPONSE_HANDSHAKE_INIT.server_random', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='login_msg.MSG_RESPONSE_HANDSHAKE_INIT.public_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=554,
  serialized_end=647,
)


_MSG_REQUEST_HANDSHAKE_ESTABLISHED = _descriptor.Descriptor(
  name='MSG_REQUEST_HANDSHAKE_ESTABLISHED',
  full_name='login_msg.MSG_REQUEST_HANDSHAKE_ESTABLISHED',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypted_key', full_name='login_msg.MSG_REQUEST_HANDSHAKE_ESTABLISHED.encrypted_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=649,
  serialized_end=707,
)


_MSG_RESPONSE_HANDSHAKE_ESTABLISHED = _descriptor.Descriptor(
  name='MSG_RESPONSE_HANDSHAKE_ESTABLISHED',
  full_name='login_msg.MSG_RESPONSE_HANDSHAKE_ESTABLISHED',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='login_msg.MSG_RESPONSE_HANDSHAKE_ESTABLISHED.status_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=709,
  serialized_end=766,
)


_MSG_REQUEST_CLIENT_LOGIN = _descriptor.Descriptor(
  name='MSG_REQUEST_CLIENT_LOGIN',
  full_name='login_msg.MSG_REQUEST_CLIENT_LOGIN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='login_msg.MSG_REQUEST_CLIENT_LOGIN.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_key', full_name='login_msg.MSG_REQUEST_CLIENT_LOGIN.session_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='login_msg.MSG_REQUEST_CLIENT_LOGIN.version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=768,
  serialized_end=849,
)


_MSG_RESPONSE_CLIENT_LOGIN = _descriptor.Descriptor(
  name='MSG_RESPONSE_CLIENT_LOGIN',
  full_name='login_msg.MSG_RESPONSE_CLIENT_LOGIN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='login_msg.MSG_RESPONSE_CLIENT_LOGIN.status_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='login_msg.MSG_RESPONSE_CLIENT_LOGIN.user_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='login_msg.MSG_RESPONSE_CLIENT_LOGIN.version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_newbie', full_name='login_msg.MSG_RESPONSE_CLIENT_LOGIN.is_newbie', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ammo', full_name='login_msg.MSG_RESPONSE_CLIENT_LOGIN.ammo', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grenades', full_name='login_msg.MSG_RESPONSE_CLIENT_LOGIN.grenades', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=852,
  serialized_end=985,
)


_MSG_REQUEST_ECHO = _descriptor.Descriptor(
  name='MSG_REQUEST_ECHO',
  full_name='login_msg.MSG_REQUEST_ECHO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value1', full_name='login_msg.MSG_REQUEST_ECHO.value1', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value2', full_name='login_msg.MSG_REQUEST_ECHO.value2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=987,
  serialized_end=1037,
)


_MSG_RESPONSE_ECHO = _descriptor.Descriptor(
  name='MSG_RESPONSE_ECHO',
  full_name='login_msg.MSG_RESPONSE_ECHO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value1', full_name='login_msg.MSG_RESPONSE_ECHO.value1', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value2', full_name='login_msg.MSG_RESPONSE_ECHO.value2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1039,
  serialized_end=1090,
)

_GAMEACCOUNTLIST.fields_by_name['game_accounts'].message_type = _GAMEACCOUNTINFO
DESCRIPTOR.message_types_by_name['GameAccountInfo'] = _GAMEACCOUNTINFO
DESCRIPTOR.message_types_by_name['GameAccountList'] = _GAMEACCOUNTLIST
DESCRIPTOR.message_types_by_name['MSG_REQUEST_ACCOUNT_LOGIN_L'] = _MSG_REQUEST_ACCOUNT_LOGIN_L
DESCRIPTOR.message_types_by_name['MSG_RESPONSE_ACCOUNT_LOGIN_L'] = _MSG_RESPONSE_ACCOUNT_LOGIN_L
DESCRIPTOR.message_types_by_name['MSG_REQUEST_HANDSHAKE_INIT'] = _MSG_REQUEST_HANDSHAKE_INIT
DESCRIPTOR.message_types_by_name['MSG_RESPONSE_HANDSHAKE_INIT'] = _MSG_RESPONSE_HANDSHAKE_INIT
DESCRIPTOR.message_types_by_name['MSG_REQUEST_HANDSHAKE_ESTABLISHED'] = _MSG_REQUEST_HANDSHAKE_ESTABLISHED
DESCRIPTOR.message_types_by_name['MSG_RESPONSE_HANDSHAKE_ESTABLISHED'] = _MSG_RESPONSE_HANDSHAKE_ESTABLISHED
DESCRIPTOR.message_types_by_name['MSG_REQUEST_CLIENT_LOGIN'] = _MSG_REQUEST_CLIENT_LOGIN
DESCRIPTOR.message_types_by_name['MSG_RESPONSE_CLIENT_LOGIN'] = _MSG_RESPONSE_CLIENT_LOGIN
DESCRIPTOR.message_types_by_name['MSG_REQUEST_ECHO'] = _MSG_REQUEST_ECHO
DESCRIPTOR.message_types_by_name['MSG_RESPONSE_ECHO'] = _MSG_RESPONSE_ECHO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameAccountInfo = _reflection.GeneratedProtocolMessageType('GameAccountInfo', (_message.Message,), {
  'DESCRIPTOR' : _GAMEACCOUNTINFO,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.GameAccountInfo)
  })
_sym_db.RegisterMessage(GameAccountInfo)

GameAccountList = _reflection.GeneratedProtocolMessageType('GameAccountList', (_message.Message,), {
  'DESCRIPTOR' : _GAMEACCOUNTLIST,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.GameAccountList)
  })
_sym_db.RegisterMessage(GameAccountList)

MSG_REQUEST_ACCOUNT_LOGIN_L = _reflection.GeneratedProtocolMessageType('MSG_REQUEST_ACCOUNT_LOGIN_L', (_message.Message,), {
  'DESCRIPTOR' : _MSG_REQUEST_ACCOUNT_LOGIN_L,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.MSG_REQUEST_ACCOUNT_LOGIN_L)
  })
_sym_db.RegisterMessage(MSG_REQUEST_ACCOUNT_LOGIN_L)

MSG_RESPONSE_ACCOUNT_LOGIN_L = _reflection.GeneratedProtocolMessageType('MSG_RESPONSE_ACCOUNT_LOGIN_L', (_message.Message,), {
  'DESCRIPTOR' : _MSG_RESPONSE_ACCOUNT_LOGIN_L,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.MSG_RESPONSE_ACCOUNT_LOGIN_L)
  })
_sym_db.RegisterMessage(MSG_RESPONSE_ACCOUNT_LOGIN_L)

MSG_REQUEST_HANDSHAKE_INIT = _reflection.GeneratedProtocolMessageType('MSG_REQUEST_HANDSHAKE_INIT', (_message.Message,), {
  'DESCRIPTOR' : _MSG_REQUEST_HANDSHAKE_INIT,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.MSG_REQUEST_HANDSHAKE_INIT)
  })
_sym_db.RegisterMessage(MSG_REQUEST_HANDSHAKE_INIT)

MSG_RESPONSE_HANDSHAKE_INIT = _reflection.GeneratedProtocolMessageType('MSG_RESPONSE_HANDSHAKE_INIT', (_message.Message,), {
  'DESCRIPTOR' : _MSG_RESPONSE_HANDSHAKE_INIT,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.MSG_RESPONSE_HANDSHAKE_INIT)
  })
_sym_db.RegisterMessage(MSG_RESPONSE_HANDSHAKE_INIT)

MSG_REQUEST_HANDSHAKE_ESTABLISHED = _reflection.GeneratedProtocolMessageType('MSG_REQUEST_HANDSHAKE_ESTABLISHED', (_message.Message,), {
  'DESCRIPTOR' : _MSG_REQUEST_HANDSHAKE_ESTABLISHED,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.MSG_REQUEST_HANDSHAKE_ESTABLISHED)
  })
_sym_db.RegisterMessage(MSG_REQUEST_HANDSHAKE_ESTABLISHED)

MSG_RESPONSE_HANDSHAKE_ESTABLISHED = _reflection.GeneratedProtocolMessageType('MSG_RESPONSE_HANDSHAKE_ESTABLISHED', (_message.Message,), {
  'DESCRIPTOR' : _MSG_RESPONSE_HANDSHAKE_ESTABLISHED,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.MSG_RESPONSE_HANDSHAKE_ESTABLISHED)
  })
_sym_db.RegisterMessage(MSG_RESPONSE_HANDSHAKE_ESTABLISHED)

MSG_REQUEST_CLIENT_LOGIN = _reflection.GeneratedProtocolMessageType('MSG_REQUEST_CLIENT_LOGIN', (_message.Message,), {
  'DESCRIPTOR' : _MSG_REQUEST_CLIENT_LOGIN,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.MSG_REQUEST_CLIENT_LOGIN)
  })
_sym_db.RegisterMessage(MSG_REQUEST_CLIENT_LOGIN)

MSG_RESPONSE_CLIENT_LOGIN = _reflection.GeneratedProtocolMessageType('MSG_RESPONSE_CLIENT_LOGIN', (_message.Message,), {
  'DESCRIPTOR' : _MSG_RESPONSE_CLIENT_LOGIN,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.MSG_RESPONSE_CLIENT_LOGIN)
  })
_sym_db.RegisterMessage(MSG_RESPONSE_CLIENT_LOGIN)

MSG_REQUEST_ECHO = _reflection.GeneratedProtocolMessageType('MSG_REQUEST_ECHO', (_message.Message,), {
  'DESCRIPTOR' : _MSG_REQUEST_ECHO,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.MSG_REQUEST_ECHO)
  })
_sym_db.RegisterMessage(MSG_REQUEST_ECHO)

MSG_RESPONSE_ECHO = _reflection.GeneratedProtocolMessageType('MSG_RESPONSE_ECHO', (_message.Message,), {
  'DESCRIPTOR' : _MSG_RESPONSE_ECHO,
  '__module__' : 'login_msg_pb2'
  # @@protoc_insertion_point(class_scope:login_msg.MSG_RESPONSE_ECHO)
  })
_sym_db.RegisterMessage(MSG_RESPONSE_ECHO)


# @@protoc_insertion_point(module_scope)
