// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY SCRIPT, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Source: apie.tbl_mail_recoverer
// ---------------------------------------------------------------------

#pragma once

#include <algorithm>
#include <cstdlib>
#include <iostream>
#include <map>
#include <memory>
#include <string>
#include <tuple>
#include <vector>

#include "apie.h"

namespace apie {
namespace dbt_role {

class tbl_mail_recoverer_AutoGen
    : public DeclarativeBase,
      public std::enable_shared_from_this<tbl_mail_recoverer_AutoGen> {

  using InsertCB =
      std::function<void(apie::status::Status, bool, uint64_t, uint64_t)>;
  using UpdateCB = std::function<void(apie::status::Status, bool, uint64_t)>;
  using DeleteCB = std::function<void(apie::status::Status, bool, uint64_t)>;

private:
  struct db_fields {
    int64_t id;
    int64_t user_id = 0;
    std::string title = "";
    int32_t title_id = 0;
    std::string title_param;
    uint16_t type;
    int32_t guild_id = 0;
    int64_t src_user_id;
    int32_t src_user_job_id = 0;
    std::string user_name = "";
    std::string memo = "";
    int32_t memo_id = 0;
    std::string memo_param;
    std::string reward_param;
    int64_t create_time = 0;
    int32_t is_multi_lang = 0;
    std::string title_lang_cn = "";
    std::string title_lang_en = "";
    std::string content_lang_cn = "";
    std::string content_lang_en = "";
    int32_t save_flag = 0;
  };

  virtual std::string getFieldName(uint32_t iIndex) override {

    static std::map<uint32_t, std::string> kFieldNameMap = {
        {tbl_mail_recoverer_AutoGen::id, "id"},
        {tbl_mail_recoverer_AutoGen::user_id, "user_id"},
        {tbl_mail_recoverer_AutoGen::title, "title"},
        {tbl_mail_recoverer_AutoGen::title_id, "title_id"},
        {tbl_mail_recoverer_AutoGen::title_param, "title_param"},
        {tbl_mail_recoverer_AutoGen::type, "type"},
        {tbl_mail_recoverer_AutoGen::guild_id, "guild_id"},
        {tbl_mail_recoverer_AutoGen::src_user_id, "src_user_id"},
        {tbl_mail_recoverer_AutoGen::src_user_job_id, "src_user_job_id"},
        {tbl_mail_recoverer_AutoGen::user_name, "user_name"},
        {tbl_mail_recoverer_AutoGen::memo, "memo"},
        {tbl_mail_recoverer_AutoGen::memo_id, "memo_id"},
        {tbl_mail_recoverer_AutoGen::memo_param, "memo_param"},
        {tbl_mail_recoverer_AutoGen::reward_param, "reward_param"},
        {tbl_mail_recoverer_AutoGen::create_time, "create_time"},
        {tbl_mail_recoverer_AutoGen::is_multi_lang, "is_multi_lang"},
        {tbl_mail_recoverer_AutoGen::title_lang_cn, "title_lang_cn"},
        {tbl_mail_recoverer_AutoGen::title_lang_en, "title_lang_en"},
        {tbl_mail_recoverer_AutoGen::content_lang_cn, "content_lang_cn"},
        {tbl_mail_recoverer_AutoGen::content_lang_en, "content_lang_en"},
        {tbl_mail_recoverer_AutoGen::save_flag, "save_flag"}};

    return kFieldNameMap[iIndex];
  }

public:
  enum Fields {
    id = 0,
    user_id = 1,
    title = 2,
    title_id = 3,
    title_param = 4,
    type = 5,
    guild_id = 6,
    src_user_id = 7,
    src_user_job_id = 8,
    user_name = 9,
    memo = 10,
    memo_id = 11,
    memo_param = 12,
    reward_param = 13,
    create_time = 14,
    is_multi_lang = 15,
    title_lang_cn = 16,
    title_lang_en = 17,
    content_lang_cn = 18,
    content_lang_en = 19,
    save_flag = 20,
  };

  static std::shared_ptr<tbl_mail_recoverer_AutoGen> Create(int64_t id) {
    return std::shared_ptr<tbl_mail_recoverer_AutoGen>(
        new tbl_mail_recoverer_AutoGen(id));
  }

  tbl_mail_recoverer_AutoGen(int64_t id) {
    this->fields.id = id;

    this->bindTable(DeclarativeBase::DBType::DBT_Role, getFactoryName());
  }

  virtual ~tbl_mail_recoverer_AutoGen() {}

  void set_id(int64_t id) {
    this->fields.id = id;
    this->markDirty({tbl_mail_recoverer_AutoGen::id});
  }

  int64_t get_id() const { return this->fields.id; }

  void set_user_id(int64_t user_id) {
    this->fields.user_id = user_id;
    this->markDirty({tbl_mail_recoverer_AutoGen::user_id});
  }

  int64_t get_user_id() const { return this->fields.user_id; }

  void set_title(std::string title) {
    this->fields.title = title;
    this->markDirty({tbl_mail_recoverer_AutoGen::title});
  }

  std::string get_title() const { return this->fields.title; }

  void set_title_id(int32_t title_id) {
    this->fields.title_id = title_id;
    this->markDirty({tbl_mail_recoverer_AutoGen::title_id});
  }

  int32_t get_title_id() const { return this->fields.title_id; }

  void set_title_param(std::string title_param) {
    this->fields.title_param = title_param;
    this->markDirty({tbl_mail_recoverer_AutoGen::title_param});
  }

  std::string get_title_param() const { return this->fields.title_param; }

  void set_type(uint16_t type) {
    this->fields.type = type;
    this->markDirty({tbl_mail_recoverer_AutoGen::type});
  }

  uint16_t get_type() const { return this->fields.type; }

  void set_guild_id(int32_t guild_id) {
    this->fields.guild_id = guild_id;
    this->markDirty({tbl_mail_recoverer_AutoGen::guild_id});
  }

  int32_t get_guild_id() const { return this->fields.guild_id; }

  void set_src_user_id(int64_t src_user_id) {
    this->fields.src_user_id = src_user_id;
    this->markDirty({tbl_mail_recoverer_AutoGen::src_user_id});
  }

  int64_t get_src_user_id() const { return this->fields.src_user_id; }

  void set_src_user_job_id(int32_t src_user_job_id) {
    this->fields.src_user_job_id = src_user_job_id;
    this->markDirty({tbl_mail_recoverer_AutoGen::src_user_job_id});
  }

  int32_t get_src_user_job_id() const { return this->fields.src_user_job_id; }

  void set_user_name(std::string user_name) {
    this->fields.user_name = user_name;
    this->markDirty({tbl_mail_recoverer_AutoGen::user_name});
  }

  std::string get_user_name() const { return this->fields.user_name; }

  void set_memo(std::string memo) {
    this->fields.memo = memo;
    this->markDirty({tbl_mail_recoverer_AutoGen::memo});
  }

  std::string get_memo() const { return this->fields.memo; }

  void set_memo_id(int32_t memo_id) {
    this->fields.memo_id = memo_id;
    this->markDirty({tbl_mail_recoverer_AutoGen::memo_id});
  }

  int32_t get_memo_id() const { return this->fields.memo_id; }

  void set_memo_param(std::string memo_param) {
    this->fields.memo_param = memo_param;
    this->markDirty({tbl_mail_recoverer_AutoGen::memo_param});
  }

  std::string get_memo_param() const { return this->fields.memo_param; }

  void set_reward_param(std::string reward_param) {
    this->fields.reward_param = reward_param;
    this->markDirty({tbl_mail_recoverer_AutoGen::reward_param});
  }

  std::string get_reward_param() const { return this->fields.reward_param; }

  void set_create_time(int64_t create_time) {
    this->fields.create_time = create_time;
    this->markDirty({tbl_mail_recoverer_AutoGen::create_time});
  }

  int64_t get_create_time() const { return this->fields.create_time; }

  void set_is_multi_lang(int32_t is_multi_lang) {
    this->fields.is_multi_lang = is_multi_lang;
    this->markDirty({tbl_mail_recoverer_AutoGen::is_multi_lang});
  }

  int32_t get_is_multi_lang() const { return this->fields.is_multi_lang; }

  void set_title_lang_cn(std::string title_lang_cn) {
    this->fields.title_lang_cn = title_lang_cn;
    this->markDirty({tbl_mail_recoverer_AutoGen::title_lang_cn});
  }

  std::string get_title_lang_cn() const { return this->fields.title_lang_cn; }

  void set_title_lang_en(std::string title_lang_en) {
    this->fields.title_lang_en = title_lang_en;
    this->markDirty({tbl_mail_recoverer_AutoGen::title_lang_en});
  }

  std::string get_title_lang_en() const { return this->fields.title_lang_en; }

  void set_content_lang_cn(std::string content_lang_cn) {
    this->fields.content_lang_cn = content_lang_cn;
    this->markDirty({tbl_mail_recoverer_AutoGen::content_lang_cn});
  }

  std::string get_content_lang_cn() const {
    return this->fields.content_lang_cn;
  }

  void set_content_lang_en(std::string content_lang_en) {
    this->fields.content_lang_en = content_lang_en;
    this->markDirty({tbl_mail_recoverer_AutoGen::content_lang_en});
  }

  std::string get_content_lang_en() const {
    return this->fields.content_lang_en;
  }

  void set_save_flag(int32_t save_flag) {
    this->fields.save_flag = save_flag;
    this->markDirty({tbl_mail_recoverer_AutoGen::save_flag});
  }

  int32_t get_save_flag() const { return this->fields.save_flag; }

public:
  void SetDbProxyServer(::rpc_msg::CHANNEL server) { m_optServer = server; }

  void Insert(InsertCB cb = nullptr) {
    if (!m_optServer.has_value()) {
      ASYNC_PIE_LOG(
          PIE_ERROR,
          "DBOpreateError | Insert | isBind:{} | dbName:{} | tableName:{}",
          isBind(), getgDbName(), getTableName());
      return;
    }

    auto channel = m_optServer.value();
    InsertToDb(channel, *this, cb);
  }

  void Update(UpdateCB cb = nullptr) {
    if (!m_optServer.has_value()) {
      ASYNC_PIE_LOG(
          PIE_ERROR,
          "DBOpreateError | Update | isBind:{} | dbName:{} | tableName:{}",
          isBind(), getgDbName(), getTableName());
      return;
    }

    auto channel = m_optServer.value();
    UpdateToDb(channel, *this, cb);
  }

  void Delete(DeleteCB cb = nullptr) {
    if (!m_optServer.has_value()) {
      ASYNC_PIE_LOG(
          PIE_ERROR,
          "DBOpreateError | Delete | isBind:{} | dbName:{} | tableName:{}",
          isBind(), getgDbName(), getTableName());
      return;
    }

    auto channel = m_optServer.value();
    DeleteFromDb(channel, *this, cb);
  }

  DAO_DEFINE_TYPE_INTRUSIVE_MACRO(tbl_mail_recoverer_AutoGen, db_fields,
                                  tbl_mail_recoverer);
};

} // namespace dbt_role

APIE_REGISTER_TABLE(DeclarativeBase::DBType::DBT_Role,
                    apie::dbt_role::tbl_mail_recoverer_AutoGen,
                    tbl_mail_recoverer)

} // namespace apie
